// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230516103542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Models.Administrator", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SlikaKorisnika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("OnlineShop.Models.Artikal", b =>
                {
                    b.Property<int>("IDArtikla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDArtikla"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("KorisnickoImeProdavca")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SlikaArtikla")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IDArtikla");

                    b.HasIndex("KorisnickoImeProdavca");

                    b.ToTable("Artikal");
                });

            modelBuilder.Entity("OnlineShop.Models.Kupac", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImeAdministratora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SlikaKorisnika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("OnlineShop.Models.Porudzbina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoImeKupca")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProdavacKorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeDostave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePorudzbine")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KorisnickoImeKupca");

                    b.HasIndex("ProdavacKorisnickoIme");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("OnlineShop.Models.PorudzbinaArtikal", b =>
                {
                    b.Property<int>("IdPorudzbine")
                        .HasColumnType("int");

                    b.Property<int>("IdArtikla")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaArtikla")
                        .HasColumnType("int");

                    b.Property<int>("PorudzbinaId")
                        .HasColumnType("int");

                    b.Property<int>("UkupnaCenaArtikala")
                        .HasColumnType("int");

                    b.HasKey("IdPorudzbine", "IdArtikla");

                    b.HasIndex("IdArtikla");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("PorudzbinaArtikli");
                });

            modelBuilder.Entity("OnlineShop.Models.Prodavac", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministratorKorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImeAdministratora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SlikaKorisnika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Verifikovan")
                        .HasColumnType("int");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("AdministratorKorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Prodavci");
                });

            modelBuilder.Entity("OnlineShop.Models.Artikal", b =>
                {
                    b.HasOne("OnlineShop.Models.Prodavac", "Prodavac")
                        .WithMany("Artikli")
                        .HasForeignKey("KorisnickoImeProdavca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodavac");
                });

            modelBuilder.Entity("OnlineShop.Models.Kupac", b =>
                {
                    b.HasOne("OnlineShop.Models.Administrator", "Administrator")
                        .WithMany("Kupci")
                        .HasForeignKey("KorisnickoIme")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("OnlineShop.Models.Porudzbina", b =>
                {
                    b.HasOne("OnlineShop.Models.Kupac", "Kupac")
                        .WithMany("Porudzbine")
                        .HasForeignKey("KorisnickoImeKupca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineShop.Models.Prodavac", null)
                        .WithMany("Porudzbina")
                        .HasForeignKey("ProdavacKorisnickoIme");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("OnlineShop.Models.PorudzbinaArtikal", b =>
                {
                    b.HasOne("OnlineShop.Models.Artikal", "Artikal")
                        .WithMany("PorudzbinaArtikli")
                        .HasForeignKey("IdArtikla")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineShop.Models.Porudzbina", "Porudzbina")
                        .WithMany("PorudzbinaArtikli")
                        .HasForeignKey("PorudzbinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("OnlineShop.Models.Prodavac", b =>
                {
                    b.HasOne("OnlineShop.Models.Administrator", "Administrator")
                        .WithMany("Prodavci")
                        .HasForeignKey("AdministratorKorisnickoIme")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("OnlineShop.Models.Administrator", b =>
                {
                    b.Navigation("Kupci");

                    b.Navigation("Prodavci");
                });

            modelBuilder.Entity("OnlineShop.Models.Artikal", b =>
                {
                    b.Navigation("PorudzbinaArtikli");
                });

            modelBuilder.Entity("OnlineShop.Models.Kupac", b =>
                {
                    b.Navigation("Porudzbine");
                });

            modelBuilder.Entity("OnlineShop.Models.Porudzbina", b =>
                {
                    b.Navigation("PorudzbinaArtikli");
                });

            modelBuilder.Entity("OnlineShop.Models.Prodavac", b =>
                {
                    b.Navigation("Artikli");

                    b.Navigation("Porudzbina");
                });
#pragma warning restore 612, 618
        }
    }
}
